baseURL = "https://www.nateconroy.com/"
languageCode = "en-us"
title = "Nate Conroy"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.nav]]
name    = "resume"
url     = "pdfs/NathanConroyResume.pdf"
weight  = 2
# [[menu.nav]]
# name    = "projects"
# url     = "gallery"
# weight  = 3
[[menu.nav]]
name    = "github"
url     = "https://github.com/NateConroy1"
weight  = 3
[[menu.nav]]
name    = "linkedin"
url     = "https://www.linkedin.com/in/nconroy/"
weight  = 4
[[menu.nav]]
name    = "email"
url     = "mailto:conroy.nathanm@gmail.com"
weight  = 5

# Site Params
[params]
home = "Home"
# Meta data
description = "Software Engineer based out of San Francisco, CA"
author = "Nate Conroy"
# Google Analytics
googleAnalitycsID = "UA-176408435-2"

# Banner Section
[params.banner]
enable  = true
bgImage = "images/tyler_blur.png"
sigImage = "images/whiteSig.svg"
description = "Software Engineer based out of San Francisco, CA"

# Homepage About Section
[params.about]
enable  = true
title   = "Hi, I'm Nate."
content = "I'm a Syracuse, NY native and an alumnus of the University of Rochester, where I graduated with a Bachelor of Science in Computer Science and a concentration in Human-Computer Interaction. Throughout my career I have grown as a reliable developer, faced with the challenge of fast paced agile environments in which I was expected to write efficient and sustainable code for extremely high traffic services with rigid release schedules. My interests include backend and web application development, balancing my love/hate relationship with distance running, and craft beer (not necessarily in that order).<br><br>Prior to San Francisco I was living in Boston, where I was working as a software engineer at Amazon for Alexa’s automated speech recognition engine. I worked to develop and support new features for the cloud speech-to-text engine that reduced latency and improved recognition accuracy for customers around the world. I gained valuable operational experience in this role as a member of our on-call rotation, in which I investigated and resolved issues that posed risks of delaying critical software releases and impacting customer experience. I was also a member of the release team responsible for deploying new engine versions to production.<br><br>During college I also worked as an intern at Amazon Web Services and Lockheed Martin, where I was fortunate to have been mentored by passionate and talented veterans in my field. I've come to love open-ended problems, and I enjoy the challenge of learning new languages, frameworks, and other technologies."
image   = "images/nate.jpeg"

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "https://www.facebook.com/nate.conroy1"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "https://www.instagram.com/nateconroy1/"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "https://www.linkedin.com/in/nconroy/"
